version: '3.7'
services:
  eventsource-mysql:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/1.sql:ro
    restart: always
    environment:
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=eventsource
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=eventsource
    ports:
      - 3306:3306

  eventsource-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  eventsource-kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: eventsource-zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: topic.clients:1:1
    depends_on:
      - eventsource-zookeeper

  eventsource-mongodb:
    image: mongo:latest
    volumes:
      - ./data/mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
